name: Build Push Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: piyushj01/html-site

jobs:

# -------------------------
# 1. BUILD + PUSH TO DOCKER HUB
# -------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

# -------------------------
# 2. DEPLOY VIA SSH (PASSWORD LOGIN)
# -------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy via SSH Password
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

            echo "Pulling latest Docker image..."
            docker pull piyushj01/html-site:latest

            echo "Stopping old container..."
            docker stop html-site || true
            docker rm html-site || true

            echo "Starting new container..."
            docker run -d -p 80:80 --name html-site piyushj01/html-site:latest

            echo "Deployment successful 🚀"
          EOF
